export interface SplitPreset {
  id: string;
  name: string;
  icon: string;
  ruleSets: { tag: string; url: string }[];
  defaultOutbound: string;
}

const GEOSITE_BASE = 'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite';
const GEOIP_BASE = 'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip';
const GEOIP_LITE_BASE = 'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo-lite/geoip';

function geosite(name: string) {
  return { tag: `geosite-${name}`, url: `${GEOSITE_BASE}/${name}.srs` };
}

function geoip(name: string) {
  return { tag: `geoip-${name}`, url: `${GEOIP_BASE}/${name}.srs` };
}

export const SPLIT_PRESETS: SplitPreset[] = [
  {
    id: 'openai',
    name: 'OpenAI',
    icon: '🤖',
    ruleSets: [
      { tag: 'geosite-openai', url: 'https://testingcf.jsdelivr.net/gh/Toperlock/sing-box-geosite@main/rule/OpenAI.srs' },
    ],
    defaultOutbound: 'proxy',
  },
  {
    id: 'anthropic',
    name: 'Anthropic/Claude',
    icon: '🧠',
    ruleSets: [geosite('anthropic')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'google',
    name: 'Google/YouTube',
    icon: '▶️',
    ruleSets: [
      geosite('youtube'),
      geoip('google'),
      geosite('google'),
      geosite('github'),
    ],
    defaultOutbound: 'proxy',
  },
  {
    id: 'telegram',
    name: 'Telegram',
    icon: '✈️',
    ruleSets: [geoip('telegram'), geosite('telegram')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'twitter',
    name: 'Twitter/X',
    icon: '🐦',
    ruleSets: [geoip('twitter'), geosite('twitter')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'facebook',
    name: 'Facebook/Instagram',
    icon: '👤',
    ruleSets: [geoip('facebook'), geosite('facebook')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'netflix',
    name: 'Netflix',
    icon: '🎬',
    ruleSets: [geoip('netflix'), geosite('netflix')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'disney',
    name: 'Disney+',
    icon: '🏰',
    ruleSets: [geosite('disney')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'spotify',
    name: 'Spotify',
    icon: '🎵',
    ruleSets: [geosite('spotify')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    icon: '🎶',
    ruleSets: [geosite('tiktok')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'apple',
    name: 'Apple',
    icon: '🍎',
    ruleSets: [
      { tag: 'geoip-apple', url: `${GEOIP_LITE_BASE}/apple.srs` },
      geosite('apple'),
      geosite('amazon'),
    ],
    defaultOutbound: 'proxy',
  },
  {
    id: 'microsoft',
    name: 'Microsoft',
    icon: '🪟',
    ruleSets: [geosite('microsoft')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'games',
    name: 'Games',
    icon: '🎮',
    ruleSets: [geosite('category-games')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'streaming',
    name: 'Streaming (HBO/Prime)',
    icon: '📺',
    ruleSets: [geosite('hbo'), geosite('primevideo')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'bilibili',
    name: 'BiliBili',
    icon: '📱',
    ruleSets: [geosite('bilibili')],
    defaultOutbound: 'direct',
  },
  {
    id: 'global',
    name: 'Global (non-CN)',
    icon: '🌐',
    ruleSets: [geosite('geolocation-!cn')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'china',
    name: 'China',
    icon: '🇨🇳',
    ruleSets: [geoip('cn'), geosite('cn')],
    defaultOutbound: 'direct',
  },
  {
    id: 'reddit',
    name: 'Reddit',
    icon: '👽',
    ruleSets: [geosite('reddit')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'discord',
    name: 'Discord',
    icon: '🎮',
    ruleSets: [geosite('discord')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'twitch',
    name: 'Twitch',
    icon: '🟣',
    ruleSets: [geosite('twitch')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp',
    icon: '💬',
    ruleSets: [geosite('whatsapp')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'line',
    name: 'LINE',
    icon: '💚',
    ruleSets: [geosite('line')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'signal',
    name: 'Signal',
    icon: '🔒',
    ruleSets: [geosite('signal')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    icon: '💼',
    ruleSets: [geosite('linkedin')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'pinterest',
    name: 'Pinterest',
    icon: '📌',
    ruleSets: [geosite('pinterest')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'steam',
    name: 'Steam',
    icon: '🕹️',
    ruleSets: [geosite('steam')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'epicgames',
    name: 'Epic Games',
    icon: '🎯',
    ruleSets: [geosite('epicgames')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'playstation',
    name: 'PlayStation',
    icon: '🎮',
    ruleSets: [geosite('playstation')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'xbox',
    name: 'Xbox',
    icon: '🎮',
    ruleSets: [geosite('xbox')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'nintendo',
    name: 'Nintendo',
    icon: '🍄',
    ruleSets: [geosite('nintendo')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'notion',
    name: 'Notion',
    icon: '📝',
    ruleSets: [geosite('notion')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'dropbox',
    name: 'Dropbox',
    icon: '📦',
    ruleSets: [geosite('dropbox')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'onedrive',
    name: 'OneDrive',
    icon: '☁️',
    ruleSets: [geosite('onedrive')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'github',
    name: 'GitHub',
    icon: '🐙',
    ruleSets: [geosite('github')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    icon: '🦊',
    ruleSets: [geosite('gitlab')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'zoom',
    name: 'Zoom',
    icon: '📹',
    ruleSets: [geosite('zoom')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'slack',
    name: 'Slack',
    icon: '💼',
    ruleSets: [geosite('slack')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'imgur',
    name: 'Imgur',
    icon: '🖼️',
    ruleSets: [geosite('imgur')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'medium',
    name: 'Medium',
    icon: '✍️',
    ruleSets: [geosite('medium')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'quora',
    name: 'Quora',
    icon: '❓',
    ruleSets: [geosite('quora')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'wikipedia',
    name: 'Wikipedia',
    icon: '📖',
    ruleSets: [geosite('wikimedia')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'soundcloud',
    name: 'SoundCloud',
    icon: '🎧',
    ruleSets: [geosite('soundcloud')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'deezer',
    name: 'Deezer',
    icon: '🎵',
    ruleSets: [geosite('deezer')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'tidal',
    name: 'Tidal',
    icon: '🌊',
    ruleSets: [geosite('tidal')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'hulu',
    name: 'Hulu',
    icon: '📺',
    ruleSets: [geosite('hulu')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'hbo',
    name: 'HBO Max',
    icon: '🎬',
    ruleSets: [geosite('hbo')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'crunchyroll',
    name: 'Crunchyroll',
    icon: '🍥',
    ruleSets: [geosite('showtimeanytime')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'imdb',
    name: 'IMDb',
    icon: '🎥',
    ruleSets: [geosite('imdb')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'craigslist',
    name: 'Craigslist',
    icon: '📋',
    ruleSets: [geosite('craigslist')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'ebay',
    name: 'eBay',
    icon: '🛒',
    ruleSets: [geosite('ebay')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'amazon',
    name: 'Amazon',
    icon: '📦',
    ruleSets: [geosite('amazon')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'walmart',
    name: 'Walmart',
    icon: '🏬',
    ruleSets: [geosite('walmart')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'shopee',
    name: 'Shopee',
    icon: '🛍️',
    ruleSets: [geosite('shopee')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'paypal',
    name: 'PayPal',
    icon: '💳',
    ruleSets: [geosite('paypal')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'stripe',
    name: 'Stripe',
    icon: '💰',
    ruleSets: [geosite('stripe')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'coursera',
    name: 'Coursera',
    icon: '🎓',
    ruleSets: [geosite('coursera')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'udemy',
    name: 'Udemy',
    icon: '📚',
    ruleSets: [geosite('udemy')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'duolingo',
    name: 'Duolingo',
    icon: '🦉',
    ruleSets: [geosite('duolingo')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'grok',
    name: 'Grok (xAI)',
    icon: '🤖',
    ruleSets: [geosite('xai')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    icon: '♊',
    ruleSets: [geosite('google-gemini')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    icon: '🔍',
    ruleSets: [geosite('deepseek')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'perplexity',
    name: 'Perplexity AI',
    icon: '❔',
    ruleSets: [geosite('perplexity')],
    defaultOutbound: 'proxy',
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    icon: '🤗',
    ruleSets: [geosite('huggingface')],
    defaultOutbound: 'proxy',
  },
];
